### PR TITLE
Change to Mozilla Public License Version 2.0 license

### PR DESCRIPTION
**Pull request by xerpi**

### CODE REVIEW

**Comment by 173210** [comment]
Agreed: @xerpi @tomtomdu80 @frangarcj 
Not confirmed: @Hykem @joshaxey @psxdev @MysteryDash
Please tell me whether you agree if you have not done ASAP!

**Comment by joshaxey** [comment]
Agreed.

**Comment by Hykem** [comment]
I agree as well.

**Comment by MysteryDash** [comment]
Okay.

**Pull request merged**
