### PR TITLE
Add TOUCH_PORT_FRONT and TOUCH_PORT_BACK number

### PR DESCRIPTION
**Pull request by ribbid987**
Add Controller mode number
Fix SceCtrlData like xerpi Helloworld

### CODE REVIEW

**Comment by xerpi** [comment]
Yes! I was just about to write a patch about the missing member in SceCtrlData!

**Comment by ribbid987** [comment]
Yeah. This makes sense. Thx.

**Comment by 173210** [comment]
I don't know why did you add numbers. uint64_t timeStamp makes sense.

**Comment by 173210** [comment]
Commit 6903f530b5ba34b1e86c7fd91eea1152c1b62990 has been cherry-picked with commit 2199fb9c15ce865c3e3e39eea32bf96ff7209c44

**Pull request closed without merging**
