### PR TITLE
Add CMake port of autotools build system

### PR DESCRIPTION
**Pull request by Ryp**
Works like the autotools build, same binaries.
The install dir is overriden to point to the build directory so you'll be able to test it easily.
I merged some of the NIDS compilation steps, (see FIXME in the code and compare with the associated Makefile.am)

### CODE REVIEW

**Comment by Ryp** [comment]
To build the `src` folder:
```bash
mkdir build-sdk
cd build-sdk
cmake ../src -DCMAKE_TOOLCHAIN_FILE=../src/cmake/arm-none-eabi-psp2.cmake -DCMAKE_BUILD_TYPE=Debug
make install -j8
```
To build the `tools` folder:
```shell
mkdir build-tools
cd build-tools
cmake ../tools -DCMAKE_BUILD_TYPE=Debug
make install -j8
```

**Comment by 173210** [comment]
It looks nice, but I have decided to use autotools because devkitPro use it.
Anyway, thank you for your work!

**Comment by Ryp** [comment]
Both build can co-exist without problems. You just closed a +3,078 LOC PR without even trying to see the benefits

**Comment by 173210** [comment]
Yes, actually it's possible. But maintaining both of them costs much power.
Hmm, if you want the CMake version to add our repository, I can make a new branch.

**Comment by Ryp** [comment]
That would be cool. That would permit people to use CLion and such, but also that could be used to integrate tests more easily for example.
My psvita isn't at home so I couldn't test any homebrew, what kind of benefit is possible when using autotools with devkitARM ?

**Comment by 173210** [comment]
This project is aiming to integrate with devkitPro, which uses autotools. Well, CI is working with autotools, to test it can be compiled easily with an environment to build devkitPro. So CI won't use CMake.

**Comment by 173210** [comment]
I added cmake branch. Can you be the maintainer?

**Comment by Ryp** [comment]
Yup

**Comment by 173210** [comment]
Now you are PSP2SDK collaborator. I hope you'll continue nice works ;)

**Pull request closed without merging**
